### ISSUE TITLE
ssh-retrieval error

### ISSUE THREAD

**Issue by hattwick** [hattwick/herdingrouters#1]
(applied_python)[phattwick@ip-172-30-0-168 main]$ python net_main.py 

Gather inventory from devices  
onePK inventory call: pynet-rtr1 cisco_ios_onepk
SSH inventory call: pynet-rtr2 cisco_ios_ssh   <<<up to here execution is working
Traceback (most recent call last):
  File "net_main.py", line 52, in <module>
    gather_inventory()
  File "net_main.py", line 25, in gather_inventory
    ssh_connect = SSHConnection(a_device)
  File "/home/phattwick/DJANGOX/main/remote_connection/ssh_connection.py", line 30, in **init**

**Comment by hattwick** [comment]
models.py was missing snap credentials, but there is still an error:

(applied_python)[phattwick@ip-172-30-0-168 main]$ python net_main.py

Gather inventory from devices
onePK inventory call: pynet-rtr1 cisco_ios_onepk
SSH inventory call: pynet-rtr2 cisco_ios_ssh
Traceback (most recent call last):
  File "/home/phattwick/DJANGOX/main/remote_connection/ssh_connection.py", line 30, in **init**
    self.username = net_device.credentials.username
AttributeError: 'NoneType' object has no attribute 'username'
(applied_python)[phattwick@ip-172-30-0-168 main]$
